### ISSUE TITLE
用官方给的权重来推理，推理结果十分混乱

### ISSUE THREAD

**Issue by wjpstudy** [fh2019ustc/PolySnake#11]
cuda环境编译成功之后，我分别尝试了
1. 在[Baidu Cloud](https://pan.baidu.com/s/1k-6HyN6Hj9KvGF-ehntYAg?pwd=l4b2)上下载了coco预训练模型，并将其放入 $ROOT/data/model/snake/coco/,运行Demo:python run.py --type demo --cfg_file configs/coco_snake.yaml demo_path demo_images ct_score 0.3, 
2. 在[Baidu Cloud](https://pan.baidu.com/s/1k-6HyN6Hj9KvGF-ehntYAg?pwd=l4b2)上下载了sbd预训练模型，并将其放入 $ROOT/data/model/snake/sbd/,运行Demo:python run.py --type demo --cfg_file configs/sbd_snake.yaml demo_path demo_images ct_score 0.3, 
在 $ROOT/demo_out/ 中结果都很十分混乱，如下：
![image](https://github.com/fh2019ustc/PolySnake/assets/93515310/7a076052-7d1a-439d-9b68-3fc3e21922d4)
![image](https://github.com/fh2019ustc/PolySnake/assets/93515310/b41bc705-e4a4-4685-87b3-baa35f07d965)
![image](https://github.com/fh2019ustc/PolySnake/assets/93515310/cd1a7e02-e550-442a-98a3-170cb5da9c61)
![image](https://github.com/fh2019ustc/PolySnake/assets/93515310/7103f624-4c83-4339-925f-ea441bb45c42)

然后我尝试着提高ct_score 0.5   ct_score 0.7  甚至是 ct_score 0.9   发现这个参数的修改，对结果没有任何的效果,请问我的问题出现在了哪里？期待您的回复，谢谢！

**Comment by fh2019ustc** [comment]
看起来像是ct_score 没有生效的问题。我最近有点忙，等我月底看看。你先debug看看~祝好

**Comment by wjpstudy** [comment]
ct_score 确实没有生效，希望能够帮忙看下是什么原因

**Comment by wjpstudy** [comment]
已解决。原因是 PolySnake/lib/networks/snake/ICD.py  中的 valid = detection[0, :, 2] >= 0.05  将ct_score写死了，改为valid = detection[0, :, 2] >= cfg.ct_score  就都正常了。
