### ISSUE TITLE
COCO训练时间

### ISSUE THREAD

**Issue by ZitengXue** [fh2019ustc/PolySnake#12]
老哥您好，我最近复现了您的代码，但是有一些不解，我的设备是双卡4090
1.训练coco batch size 为32， 1个epoch训练时间近两个小时，请问这个训练速度正常吗？感觉如果按照默认config双卡4090需要150~300小时。
2.训练KINS batch size为16 显存会不够，只能batch size为8进行训练，想问下老哥当时KINS是用什么显卡配置跑的
谢谢老哥

**Comment by fh2019ustc** [comment]
1. 正常的，COCO比较大，用3090会比2080快不少。你可以把卡数提到4，即4卡3090，把显存拉满
2. KINS我是用2080跑的，12g显存

**Comment by ZitengXue** [comment]
非常感谢老哥！
